from apps.Yugioh_Database.models import Archetype

archetypes: list = [
    "A-to-Z",
    "Abyss Actor",
    "Adamancipator",
    "Adventurer",
    "Aesir",
    "Agent",
    "Albaz",
    "Alien",
    "Ally of Justice",
    "Altergeist",
    "Amazemment",
    "Amazoness",
    "Amorphage",
    "Ancient Gear",
    "Ancient Warriors",
    "Appliancer",
    "Aquaactress",
    "Arcana Force",
    "Archfiend",
    "Armed Dragon",
    "Aroma",
    "Artifact",
    "Ashened",
    "Assault Mode",
    "Atlantean",
    "Batteryman",
    "Battlewasp",
    "Battlin Boxer",
    "Beetrooper",
    "Black Luster",
    "Blackwing",
    "Blue-Eyes",
    "Bounzer",
    "Brotherhood of the Fire Fist",
    "Bujin",
    "Burning Abyss",
    "Buster Blader",
    "Butterspy",
    "Bystial",
    "Centur-Ion",
    "Chaos",
    "Charmer",
    "Chemicritter",
    "Chronomaly",
    "Chrysalis",
    "Cipher",
    "Cloudian",
    "Code Talker",
    "Constellar",
    "Crusadia",
    "Crystal Beast",
    "Crystron",
    "Cubic",
    "Cyber",
    "Cyber Dragon",
    "Cyberdark",
    "D.D.",
    "D/D/",
    "Danger!",
    "Dark Magician",
    "Dark Scorpion",
    "Dark World",
    "Darklord",
    "Deep Sea",
    "Deskbot",
    "Despia",
    "Destiny Hero",
    "Digital Bug",
    "Dinomist",
    "Dinomorphia",
    "Dinowrestler",
    "Dododo",
    "Dogmatika",
    "Doodle Beast",
    "Dracoslayer",
    "Dragon Ruler",
    "Dragonmaid",
    "Dragunity",
    "Dream Mirror",
    "Drytron",
    "Dual Avatar",
    "Duston",
    "Earthbound",
    "Edge Imp",
    "Edlich",
    "Elemental Hero",
    "Elementsaber",
    "Empowered Warrior",
    "Endymion",
    "Evil Eye",
    "Evil Hero",
    "Evil Twin / Live Twin",
    "Evilswarm",
    "Exodia",
    "Evoltile",
    "Exosister",
    "Eyes Restrict",
    "F.A.",
    "Fabled",
    "Face Cards",
    "Fairy Tail",
    "Familiar-Possessed",
    "Fiendsmith",
    "Fire King",
    "Fire Warrior",
    "Flame Swordsman",
    "Flamvell",
    "Fleur",
    "Floowandereeze",
    "Flower Cardian",
    "Fluffal",
    "Fortune Fairy",
    "Fortune Lady",
    "Fossil Fusion",
    "Frightfur",
    "Frog",
    "Fur Hire",
    "G Golem",
    "Gadget",
    "Gagaga",
    "Gaia",
    "Galaxy",
    "Ganbara",
    "Gate Guardian",
    "Gearfried",
    "Geargia",
    "Gem-",
    "Generaider",
    "Genex",
    "Ghostrick",
    "Ghoti",
    "Gimmick Puppet",
    "Gishki",
    "Glacial Beast",
    "Gladiator Beast",
    "Goblin",
    "Goblin Biker",
    "Gogogo",
    "Gold Pride",
    "Gorgonic",
    "Gouki",
    "Goyo",
    "Gravekeeper",
    "Graydle",
    "Gunkan",
    "Gusto",
    "Harpie",
    "Hazy Flame",
    "Heraldic Beast",
    "Heroic",
    "Hieratic",
    "Horus",
    "Ice Barrier",
    "Icejade",
    "Igknight",
    "Ignister",
    "Impcantation",
    "Infernity",
    "Infernoble",
    "Infernoid",
    "Infinitrack",
    "Invoked",
    "Inzektor",
    "Iron Chain",
    "Junk",
    "Jurrac",
    "Kaiju",
    "Karakuri",
    "Kashtira",
    "Knightmare",
    "Koa'ki Meiru",
    "Kozmo",
    "Krawler",
    "Kuriboh",
    "Labrynth",
    "Laval",
    "Libromancer",
    "Lightray",
    "Lightsworn",
    "Lswarm",
    "Lunalight",
    "Lyrilusc",
    "Machina",
    "Madolche",
    "Magical Musket",
    "Magician",
    "Magikey",
    "Magistus",
    "Majespecter",
    "Malefic",
    "Maliss",
    "Mannadium",
    "Marincess",
    "Masked HERO",
    "Materiactor",
    "Mathmech",
    "Mayakashi",
    "Mecha Phantom Beast",
    "Megalith",
    "Mekk-Knight",
    "Meklord",
    "Melffy",
    "Melodious",
    "Memento",
    "Mermail",
    "Metalfoes",
    "Metalmorph",
    "Metaphys",
    "Mikanko",
    "Millennium",
    "Mimighoul",
    "Mist Valley",
    "Monarch",
    "Morphtronic",
    "Mystical Beast",
    "Mythical Beast",
    "Myutant",
    "Naturia",
    "Nekroz",
    "Nemeses",
    "Nemleria",
    "Neo-Spacian",
    "Neos",
    "Nephthys",
    "Nimble",
    "Ninja",
    "Noble Knight",
    "Nordic",
    "Nouvelles",
    "Number",
    "Numeron",
    "Odd-Eyes",
    "Ogdoadic",
    "Ojama",
    "Orcust",
    "P.U.N.K.",
    "Paleozoic",
    "Parshath",
    "Penguin",
    "Performage",
    "Performapal",
    "Phantasm Spiral",
    "Phantom Beast",
    "Photon",
    "Plunder Patroll",
    "Prank-Kids",
    "Predaplant",
    "Prediction Princess",
    "PSY-Framegear",
    "Psychic",
    "Purrely",
    "Qli",
    "Ragnaraika",
    "Raidraptor",
    "Red-Eyes",
    "Reptilianne",
    "Rescue-ACE",
    "Resonator",
    "Rikka",
    "Risebell",
    "Ritual Beast",
    "Roid",
    "Rokket",
    "Rose",
    "Runick",
    "Ryu-Ge",
    "Ryzeal ",
    "S-Force",
    "Salamangreat",
    "Sangen",
    "Scareclaw",
    "Scrap",
    "Shaddoll",
    "Shark",
    "Shining Sarcophagus",
    "Shinobird",
    "Shiranui",
    "Silent Magician",
    "Silent Swordsman",
    "Simorgh",
    "Sinful Spoils",
    "Six Samurai",
    "Skull Servant",
    "Sky Striker",
    "Snake-Eye",
    "Solfachord",
    "Speedroid",
    "Spellbook",
    "Spellcaster",
    "Sphinx",
    "Spright",
    "Springan",
    "Spyral",
    "Star Sereph",
    "Starry Knight",
    "Steelswarm",
    "Subterror",
    "Sunavalon",
    "Superheavy Samurai",
    "Supreme King",
    "Swordsoul",
    "Sylvan",
    "Symphonic Warrior",
    "Synchron",
    "T.G.",
    "Tearlaments",
    "Tellarknight",
    "Tenyi",
    "The Agent",
    "The Phantom Knights",
    "The Weather",
    "Therion",
    "Thunder Dragon",
    "Time Thief",
    "Timelord",
    "Tindangle",
    "Tistina",
    "Toon",
    "Toy",
    "Traptrix",
    "Tri-Brigade",
    "Triamid",
    "Trickstar",
    "True King",
    "Twilightsworn",
    "U.A.",
    "Unchained",
    "Ursarctic",
    "Utopia",
    "Vaalmonica",
    "Vampire",
    "Vanquish Soul",
    "Vassal",
    "Vaylantz",
    "Vendread",
    "Venom",
    "Virtual World",
    "Visas Starfrost",
    "Vision HERO",
    "Voiceless Voice",
    "Volcanic",
    "Vylon",
    "War Rock",
    "Watt",
    "White Forest",
    "Wind-up",
    "Windwitch",
    "Witchcrafter",
    "World Chalice",
    "World Legacy",
    "Worm",
    "X-Saber",
    "Xtra HERO",
    "Xyz",
    "Yang Zing",
    "Yosenju",
    "Yubel",
    "Zefra",
    "Zombie",
    "Zoodiac",
    "Zubaba",
    "ZW -",
]
for archetype in archetypes:
    archetype, created = Archetype.objects.get_or_create(archetype_name=archetype)
    print(f"{archetype} is Created: {created}")
