# Generated by Django 5.1.6 on 2025-03-12 14:28

import apps.Yugioh_Database.enums
import apps.Yugioh_Database.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Precise_effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('effects', models.ManyToManyField(to='Yugioh_Database.effect')),
                ('precise_effects', models.ManyToManyField(to='Yugioh_Database.precise_effect')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Yugioh_Database.card_description')),
                ('name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('MONSTER', 'MONSTER'), ('SPELL', 'SPELL'), ('TRAP', 'TRAP')], default='MONSTER', max_length=50)),
                ('archetypes', models.ManyToManyField(to='Yugioh_Database.archetype')),
                ('description_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card', to='Yugioh_Database.card_description')),
            ],
            bases=('Yugioh_Database.card_description',),
        ),
        migrations.CreateModel(
            name='Monster_Card',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Yugioh_Database.card')),
                ('attribute', models.CharField(choices=apps.Yugioh_Database.enums.MonsterAttributeOptions.options, default='LIGHT', max_length=50)),
                ('monster_type', models.CharField(choices=apps.Yugioh_Database.enums.MonsterTypeOptions.options, default='AQUA', max_length=50)),
                ('level_rank', models.PositiveSmallIntegerField(default=0, validators=[apps.Yugioh_Database.models.maximum_level_rank_pendscale])),
                ('pendulum_scale', models.PositiveSmallIntegerField(default=0, validators=[apps.Yugioh_Database.models.maximum_level_rank_pendscale])),
                ('link_rating', models.PositiveSmallIntegerField(default=0, validators=[apps.Yugioh_Database.models.maximum_link_rating])),
                ('attack', models.PositiveSmallIntegerField(default=0, validators=[apps.Yugioh_Database.models.maximum_battle_value])),
                ('defense', models.PositiveSmallIntegerField(default=0, validators=[apps.Yugioh_Database.models.maximum_battle_value])),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Monster_Card', to='Yugioh_Database.card')),
            ],
            bases=('Yugioh_Database.card',),
        ),
    ]
