# Generated by Django 5.1.6 on 2025-03-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell_Card',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Yugioh_Database.card')),
                ('card_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('QUICK_PLAY', 'QUICK PLAY'), ('FIELD', 'FIELD'), ('CONTINUOUS', 'CONTINUOUS'), ('EQUIP', 'EQUIP'), ('RITUAL', 'RITUAL'), ('FIELD SPELL', 'FIELD SPELL'), ('NORMAL', 'NORMAL')], default='NORMAL', max_length=50)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spell_Card', to='Yugioh_Database.card')),
            ],
            bases=('Yugioh_Database.card',),
        ),
        migrations.CreateModel(
            name='Trap_Card',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Yugioh_Database.card')),
                ('card_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('CONTINUOUS', 'CONTINUOUS'), ('COUNTER', 'COUNTER')], default='NORMAL', max_length=50)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trap_Card', to='Yugioh_Database.card')),
            ],
            bases=('Yugioh_Database.card',),
        ),
    ]
