# Generated by Django 5.1.6 on 2025-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0002_spell_card_trap_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'verbose_name': 'Archetype', 'verbose_name_plural': 'Archetypes'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='card_description',
            options={'verbose_name': 'Card Description', 'verbose_name_plural': 'Card Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='effect',
            options={'verbose_name': 'Effect', 'verbose_name_plural': 'Effects'},
        ),
        migrations.AlterModelOptions(
            name='monster_card',
            options={'verbose_name': 'Monster Card', 'verbose_name_plural': 'Monster Cards'},
        ),
        migrations.AlterModelOptions(
            name='precise_effect',
            options={'verbose_name': 'Precise Effect', 'verbose_name_plural': 'Precise Effects'},
        ),
        migrations.AlterModelOptions(
            name='spell_card',
            options={'verbose_name': 'Spell Card', 'verbose_name_plural': 'Spell Cards'},
        ),
        migrations.AlterModelOptions(
            name='trap_card',
            options={'verbose_name': 'Trap Card', 'verbose_name_plural': 'Trap Cards'},
        ),
        migrations.AddField(
            model_name='monster_card',
            name='monster_card_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('EFFECT', 'EFFECT'), ('RITUAL', 'RITUAL'), ('FUSION', 'FUSION'), ('SYNCHRO', 'SYNCHRO'), ('XYZ', 'XYZ'), ('TOON', 'TOON'), ('SPIRIT', 'SPIRIT'), ('UNION', 'UNION'), ('GEMINI', 'GEMINI'), ('TUNER', 'TUNER'), ('FLIP', 'FLIP'), ('PENDULUM', 'PENDULUM'), ('LINK', 'LINK')], default='NORMAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='monster_card',
            name='attribute',
            field=models.CharField(choices=[('LIGHT', 'LIGHT'), ('DARK', 'DARK'), ('EARTH', 'EARTH'), ('WATER', 'WATER'), ('WIND', 'WIND'), ('FIRE', 'FIRE'), ('DIVINITY', 'DIVINITY')], default='LIGHT', max_length=50),
        ),
        migrations.AlterField(
            model_name='monster_card',
            name='monster_type',
            field=models.CharField(choices=[('AQUA', 'AQUA'), ('BEAST', 'BEAST'), ('BEAST_WARRIOR', 'BEAST-WARRIOR'), ('CYBERSE', 'CYBERSE'), ('DINOSAUR', 'DINOSAUR'), ('DIVINE_BEAST', 'DIVINE BEAST'), ('DRAGON', 'DRAGON'), ('FAIRY', 'FAIRY'), ('FIEND', 'FIEND'), ('FISH', 'FISH'), ('ILLUSION', 'ILLUSION'), ('INSECT', 'INSECT'), ('MACHINE', 'MACHINE'), ('PLANT', 'PLANT'), ('PSYCHIC', 'PSYCHIC'), ('PYRO', 'PYRO'), ('REPTILE', 'REPTILE'), ('ROCK', 'ROCK'), ('SEA_SERPENT', 'SEA SERPENT'), ('SPELLCASTER', 'SPELLCASTER'), ('THUNDER', 'THUNDER'), ('WARRIOR', 'WARRIOR'), ('WINGED_BEAST', 'WINGED BEAST'), ('WYRM', 'WYRM'), ('ZOMBIE', 'ZOMBIE')], default='AQUA', max_length=50),
        ),
    ]
