# Generated by Django 5.1.6 on 2025-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0003_alter_archetype_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precise_effect',
            name='effect_category',
            field=models.ManyToManyField(related_name='Precise_Effect', to='Yugioh_Database.effect'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='effect_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('ACTIVATION AREA', 'ACTIVATION AREA'), ('ACTIVATION CONDITION', 'ACTIVATION CONDITION'), ('ACTIVATION UPON', 'ACTIVATION UPON'), ('ACTIVATION WHEN', 'ACTIVATION WHEN'), ('ACTIVATION OTHERS', 'ACTIVATION OTHERS'), ('ADD CARD', 'ADD CARD'), ('MONSTER STAT MODIFIERS', 'MONSTER STAT MODIFIERS'), ('ALLOW ACTIVATIONS', 'ALLOW ACTIVATIONS'), ('ALTER SUMMON CONDITION', 'ALTER SUMMON CONDITION'), ('APPLY EFFECT WHEN', 'APPLY EFFECT WHEN'), ('APPLY EFFECT IF', 'APPLY EFFECT IF'), ('ATTACH XYZ MATERIAL', 'ATTACH XYZ MATERIAL'), ('BANISH', 'BANISH'), ('BANISH SHIFTS LOCATION', 'BANISH SHIFTS LOCATION'), ('BANISH FUSION MATERIALS', 'BANISH FUSION MATERIALS'), ('BANISH FOR COST', 'BANISH FOR COST'), ('BANISH FOR RITUAL SUMMON', 'BANISH FOR RITUAL SUMMON'), ('BATTLE RELATED', 'BATTLE RELATED'), ('EXTERNAL SPECIAL SUMMON', 'EXTERNAL SPECIAL SUMMON'), ('', 'ACTIVATED BY EITHER PLAYER'), ('QUICK EFFECT', 'QUICK EFFECT'), ('EXTERNAL REVIVE', 'EXTERNAL REVIVE'), ('ALTERNATIVE FUSION SUMMON POSSIBLE', 'ALTERNATIVE FUSION SUMMON POSSIBLE'), ('EASIER RITUAL SUMMON', 'EASIER RITUAL SUMMON'), ('RESTRICTION TYPE', 'RESTRICTION TYPE'), ('CHAIN EFFECT', 'CHAIN EFFECT')], default='NORMAL', max_length=500),
        ),
    ]
