# Generated by Django 5.1.6 on 2025-03-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0005_alter_effect_effect_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='description_id',
            new_name='description_text',
        ),
    ]
