# Generated by Django 5.1.6 on 2025-03-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0006_rename_description_id_card_description_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description_text',
        ),
    ]
