# Generated by Django 5.1.6 on 2025-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0007_remove_card_description_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, choices=[('MONSTER', 'MONSTER'), ('SPELL', 'SPELL'), ('TRAP', 'TRAP')], default='MONSTER', max_length=50),
        ),
    ]
