# Generated by Django 5.1.6 on 2025-03-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0010_alter_effect_effect_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precise_effect',
            name='effect_category',
        ),
        migrations.AddField(
            model_name='precise_effect',
            name='effect_category',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='Precise_Effect', to='Yugioh_Database.effect'),
        ),
    ]
