# Generated by Django 5.1.6 on 2025-03-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0012_alter_effect_effect_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell_card',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='spell_card',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='trap_card',
            name='card_name',
        ),
    ]
