# Generated by Django 5.1.6 on 2025-03-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0013_remove_spell_card_card_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster_card',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='trap_card',
            name='card_id',
        ),
    ]
