# Generated by Django 5.1.6 on 2025-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0014_remove_monster_card_card_id_remove_trap_card_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='monster_card',
            name='monster_card_type',
        ),
        migrations.AddField(
            model_name='monster_card',
            name='monster_card_type',
            field=models.ManyToManyField(to='Yugioh_Database.monstercardtype'),
        ),
    ]
