# Generated by Django 5.1.6 on 2025-04-09 08:03

import apps.Yugioh_Database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugioh_Database', '0015_monstercardtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster_card',
            name='attack',
            field=models.SmallIntegerField(default=0, validators=[apps.Yugioh_Database.models.maximum_battle_value]),
        ),
        migrations.AlterField(
            model_name='monster_card',
            name='defense',
            field=models.SmallIntegerField(default=0, validators=[apps.Yugioh_Database.models.maximum_battle_value]),
        ),
    ]
